management:
  endpoints:
    web:
      exposure:
        include: loggers
  endpoint:
    loggers:
      enabled: true

logging:
  level:
    ROOT: INFO
    ru.neoflex.troubleshooting: INFO
    org.springframework: INFO
