global:
  scrape_interval: 15s

scrape_configs:

  - job_name: 'spring-actuator'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['monitoring:8080']